create table if not exists public.farmers (
  id bigint generated by default as identity primary key,
  bp_number text not null unique,
  farmer_name text,
  phone text,
  village text,
  estate text,
  employee_name text,
  cluster text,
  team text,
  day text,
  route_group text,
  visit_date date,
  latitude double precision,
  longitude double precision,
  remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.farmers add column if not exists estate text;
alter table public.farmers add column if not exists name_in_bpm text;
alter table public.farmers add column if not exists farm_name text;
alter table public.farmers add column if not exists area_under_rejuvenation text;
alter table public.farmers add column if not exists employee_name text;
alter table public.farmers add column if not exists route_group text;
alter table public.farmers add column if not exists visit_date date;
alter table public.farmers add column if not exists remarks text;

create table if not exists public.completed_farmers (
  bp_number text primary key references public.farmers(bp_number) on delete cascade,
  remarks text,
  completed_at timestamptz not null default now()
);

create table if not exists public.cluster_points (
  id bigint generated by default as identity primary key,
  cluster text not null,
  team text,
  day text,
  latitude double precision not null,
  longitude double precision not null,
  color text,
  source text default 'Cluster_Map.html',
  created_at timestamptz not null default now()
);

create index if not exists farmers_cluster_idx on public.farmers(cluster);
create index if not exists farmers_team_idx on public.farmers(team);
create index if not exists farmers_day_idx on public.farmers(day);
create index if not exists farmers_route_idx on public.farmers(route_group);
create index if not exists farmers_visit_date_idx on public.farmers(visit_date);
create index if not exists farmers_bp_idx on public.farmers(bp_number);
create index if not exists farmers_gps_idx on public.farmers(latitude,longitude);
create index if not exists cluster_points_cluster_idx on public.cluster_points(cluster);
create index if not exists cluster_points_gps_idx on public.cluster_points(latitude,longitude);

alter table public.farmers enable row level security;
alter table public.completed_farmers enable row level security;
alter table public.cluster_points enable row level security;

-- The backend uses the service-role key and therefore bypasses RLS.
-- Never expose SUPABASE_SERVICE_ROLE_KEY in the browser.


-- ======================================================
-- AUTH / USER MANAGEMENT / AUDIT
-- ======================================================

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  role text not null default 'enumerator' check (role in ('admin','enumerator')),
  is_active boolean not null default true,
  last_login_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_active_idx on public.profiles(is_active);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  user_email text,
  user_name text,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_user_idx on public.audit_logs(user_id);
create index if not exists audit_logs_action_idx on public.audit_logs(action);
create index if not exists audit_logs_email_idx on public.audit_logs(user_email);
create index if not exists completed_farmers_completed_at_idx on public.completed_farmers(completed_at desc);

-- ======================================================
-- PRIVATE FARMER GROUPS
-- Each group belongs to exactly one signed-in user.
-- Members are stored by BP number; deleting a group never
-- deletes or changes the underlying farmer records.
-- ======================================================

create table if not exists public.farmer_groups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, name)
);

create table if not exists public.farmer_group_members (
  group_id bigint not null references public.farmer_groups(id) on delete cascade,
  bp_number text not null references public.farmers(bp_number) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (group_id, bp_number)
);

create index if not exists farmer_groups_user_idx
  on public.farmer_groups(user_id, created_at);

create index if not exists farmer_group_members_bp_idx
  on public.farmer_group_members(bp_number);

alter table public.farmer_groups enable row level security;
alter table public.farmer_group_members enable row level security;


alter table public.completed_farmers add column if not exists completed_by uuid references auth.users(id) on delete set null;
alter table public.completed_farmers add column if not exists completed_by_email text;

alter table public.profiles enable row level security;
alter table public.audit_logs enable row level security;

-- The browser never receives the service-role key. The backend uses the
-- service role for application data and role checks, so no public write
-- policies are required for these operational tables.


-- ======================================================
-- TEAM LOCATION SHARING
-- Enumerators can share their current device location while
-- the app is open. Admin/team members can view recent locations.
-- ======================================================

alter table public.profiles add column if not exists team text;

create table if not exists public.team_locations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  created_at timestamptz not null default now()
);

create index if not exists team_locations_user_idx on public.team_locations(user_id);
create index if not exists team_locations_created_idx on public.team_locations(created_at desc);
create index if not exists team_locations_user_created_idx on public.team_locations(user_id, created_at desc);
alter table public.team_locations enable row level security;
